import { strict as assert } from 'node:assert';
import { execFileSync, spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'node:test';

const root = fileURLToPath(new URL('..', import.meta.url));
function fixture(t) {
  const directory = mkdtempSync(join(tmpdir(), 'pmo-release-test-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  for (const file of [
    '.gitignore',
    '.env.example',
    'backend/.env.example',
    'frontend/.env.example',
    'scripts/check-docs.mjs',
    'scripts/check-release.mjs',
  ]) {
    mkdirSync(dirname(join(directory, file)), { recursive: true });
    copyFileSync(join(root, file), join(directory, file));
  }
  return directory;
}
const run = (directory, script = 'check-release.mjs') =>
  spawnSync(process.execPath, [join(directory, 'scripts', script)], {
    cwd: directory,
    encoding: 'utf8',
  });
const git = (directory, args) => execFileSync('git', args, { cwd: directory, stdio: 'pipe' });

test('safe sources pass while local environments and build artifacts stay excluded', (t) => {
  const directory = fixture(t);
  writeFileSync(join(directory, 'backend/.env'), 'PRIVATE_VALUE=local-fixture-only');
  mkdirSync(join(directory, 'frontend/.next'), { recursive: true });
  writeFileSync(join(directory, 'frontend/.next/build.log'), 'generated');
  writeFileSync(join(directory, 'frontend/next-env.d.ts'), '// Generated by Next.js');
  const before = run(directory);
  assert.equal(before.status, 0, before.stderr);
  assert.equal(
    existsSync(join(directory, '.git')),
    false,
    'preflight must not initialise the source repository',
  );
  git(directory, ['init', '-b', 'main']);
  git(directory, ['add', '.']);
  const after = run(directory);
  assert.equal(after.status, 0, after.stderr);
  git(directory, ['add', '-f', 'frontend/next-env.d.ts']);
  const forced = run(directory);
  assert.equal(forced.status, 1);
  assert.match(forced.stderr, /next-env\.d\.ts: private configuration or generated file/);
});

test('a staged token is rejected after the working copy has been cleaned, without printing its value', (t) => {
  const directory = fixture(t);
  git(directory, ['init', '-b', 'main']);
  const synthetic = 'sk-proj-' + 'x'.repeat(40);
  writeFileSync(join(directory, 'notes.txt'), synthetic);
  git(directory, ['add', 'notes.txt']);
  writeFileSync(join(directory, 'notes.txt'), 'cleaned working copy');
  const result = run(directory);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /notes\.txt \(index\): possible provider token/);
  assert.ok(!result.stderr.includes(synthetic));
});

test('an environment already in the index is rejected even though ignore rules exclude it', (t) => {
  const directory = fixture(t);
  git(directory, ['init', '-b', 'main']);
  writeFileSync(join(directory, '.env'), 'TEST_FIXTURE_ONLY=true');
  git(directory, ['add', '-f', '.env']);
  const result = run(directory);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /\.env: private configuration/);
});

test('documentation checks detect broken anchors, filename case and local links', (t) => {
  const directory = fixture(t);
  mkdirSync(join(directory, 'docs'));
  writeFileSync(join(directory, 'docs/guide.md'), '# Guide\n\n## Local setup\n');
  writeFileSync(join(directory, 'README.md'), '# Project\n\n[Guide](docs/guide.md#local-setup)\n');
  assert.equal(run(directory, 'check-docs.mjs').status, 0);
  writeFileSync(
    join(directory, 'README.md'),
    '# Project\n\n[Wrong case](docs/Guide.md)\n[Missing](docs/guide.md#missing)\n[Local](file:///private/project/guide.md)\n',
  );
  const result = run(directory, 'check-docs.mjs');
  assert.equal(result.status, 1);
  assert.match(result.stderr, /incorrect case/);
  assert.match(result.stderr, /missing heading anchor/);
  assert.match(result.stderr, /internal links must be relative/);
});
