"""Provider selection and explicit fallback, independent of auth and storage."""
from datetime import datetime, timezone
from uuid import uuid4

from app.config import Settings
from app.models.generation import GenerationRequest, GenerationResponse
from app.providers.base import ProviderError
from app.providers.demo import DemoAIProvider
from app.providers.factory import create_provider


async def generate_document(payload: GenerationRequest, settings: Settings, *, public_demo: bool = False) -> GenerationResponse:
    fallback = payload.useDemoFallback and settings.ai_provider == 'ollama' and not public_demo
    provider = DemoAIProvider() if public_demo or fallback else create_provider(settings)
    try:
        result = await provider.generate(payload)
    except ProviderError as error:
        error.provider = provider.name
        error.fallback_available = provider.name == 'ollama'
        raise
    if fallback:
        result.warnings.append(
            'Has elegido continuar con plantillas demo como alternativa a Ollama. Este documento no procede de un modelo de lenguaje.'
            if payload.language == 'es' else
            'You chose demo templates as a fallback for Ollama. This document was not generated by a language model.'
        )
    return GenerationResponse(
        **result.model_dump(), id=str(uuid4()), type=payload.type, language=payload.language,
        provider=provider.name, fallbackFrom='ollama' if fallback else None,
        generatedAt=datetime.now(timezone.utc),
    )
